# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fc2edf039d6aac066dac858341baec5af7762032e912b620ab83e03742718f4ae8a8155d761d5d14a682fa83971bcca9fbacf92f31b02d2f04219e79c28aad3

test:
  secret_key_base: 9136254ebfb95ca66df84d13624cdb5cd72671e137367fc898394552c76cc1c802b32193ca8ea8d6d30f5e04c205f21d5dbb1d4d0b37274b990448c63f391249

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
